### ISSUE TITLE
Fails to install from PyPI source: FileNotFoundError: [Errno 2] No such file or directory: './version'

### ISSUE THREAD

**Issue by andersk** [kichik/tlds#5]
The `version` file in the Git repository is missing from the source tarball on PyPI, so the package cannot be installed from source (i.e. without using the wheel):

```console
$ curl -fsL 'https://files.pythonhosted.org/packages/20/fb/3d5cd8beddeb51cbde9d3fd2121884daa1353bb42886cae62856c88a09b9/tlds-2023080900.tar.gz' | tar -tz
tlds-2023080900/
tlds-2023080900/LICENSE
tlds-2023080900/PKG-INFO
tlds-2023080900/README.rst
tlds-2023080900/setup.cfg
tlds-2023080900/setup.py
tlds-2023080900/tlds/
tlds-2023080900/tlds/__init__.py
tlds-2023080900/tlds/_data.py
tlds-2023080900/tlds.egg-info/
tlds-2023080900/tlds.egg-info/PKG-INFO
tlds-2023080900/tlds.egg-info/SOURCES.txt
tlds-2023080900/tlds.egg-info/dependency_links.txt
tlds-2023080900/tlds.egg-info/top_level.txt
tlds-2023080900/tlds.egg-info/zip-safe

$ pip install --no-binary=tlds tlds
Collecting tlds
  Using cached tlds-2023080900.tar.gz (7.8 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-7264mh51/tlds_97d58d23bcab41c6ac23a2376e96cbb9/setup.py", line 3, in <module>
          with open("./version") as fd:
      FileNotFoundError: [Errno 2] No such file or directory: './version'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by kichik** [comment]
Thanks!
